# Numpy

Criação de arrays

In [3]:
import numpy as np

zeros = np.zeros((3, 3))
print("Zeros:\n", zeros)

uns = np.ones((3, 3))
print("Uns:\n", uns)


identidade = np.eye(3)
print("Identidade:\n", identidade)


sequencia = np.arange(0, 10, 2)  # começa em 0, termina antes de 10, passo 2
print("Sequência:", sequencia)


espacados = np.linspace(0, 1, 5)  # começa em 0, termina em 1, 5 elementos
print("Espaçados igualmente:", espacados)


### atenção pois vamos precisar
randomico = np.random.randint(0, 11, (5, 3)) # números entre 0 e 10 em um 5 x 3
print("Array randomico:", randomico)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Uns:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Sequência: [0 2 4 6 8]
Espaçados igualmente: [0.   0.25 0.5  0.75 1.  ]
Array randomico: [[ 1  6  8]
 [ 1  6  0]
 [ 9  6  2]
 [10  1  2]
 [ 4  5  9]]


Operações Matemáticas

In [ ]:

a = np.array([1, 2, 3, 4])


print("Soma:", np.sum(a))
print("Produto:", np.prod(a))
print("Média:", np.mean(a))
print("Variância:", np.var(a))
print("Desvio padrão:", np.std(a))


### atenção pois vamos precisar em breve
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Soma ao longo das linhas:", np.sum(b, axis=1))


print("Soma ao longo das colunas:", np.sum(b, axis=0))

# Exercício

Você recebeu um conjunto de dados contendo as notas de 40 alunos em três disciplinas: Matemática, Ciências e História. Seu objetivo é realizar uma análise estatística e algumas transformações nos dados.

Dados:
Crie um array de dimensões 40x3 com números aleatórios entre 0 e 10 usando o módulo numpy.random. Cada linha do array representa um aluno, e as colunas representam suas notas em Matemática, Ciências e História, respectivamente.

Tarefas:

a) Calcule e imprima a média e o desvio padrão das notas de cada disciplina.

b) Determine e imprima o número de alunos que tiveram notas acima da média em todas as três disciplinas.

c) Calcule e imprima a nota mais alta e a nota mais baixa de cada disciplina.

d) Normalize as notas de modo que elas estejam no intervalo [0, 1]. A normalização é feita pela fórmula: 

nota_normalizada = (nota − nota_min) / ( nota_max − nota_min)

​
Determine e imprima o número de alunos que tiveram notas (após a normalização) abaixo de 0,5 em qualquer uma das disciplinas.


Dicas:

Utilize a funcionalidade numpy.random.randint ou numpy.random.rand para criar o array de notas.
Use funções como np.mean(), np.std(), np.min(), e np.max() para cálculos estatísticos.
Para contar alunos com base em certos critérios, você pode usar comparações booleanas e a função np.sum().

In [ ]:
# Proposta do Maxim

np.random.seed(123)

notas = np.random.randint(0, 10, (40, 3)) # notas


media = np.mean(notas, axis = 0) 
print(media) # medias
std_dev = np.std(notas, axis=0)
print(std_dev) # sd

# varrer para garantir que está maior nas três! 
# for i in range(3) :
#      print(np.sum(notas[:, i] > media[i])) # varrendo o array todo


alunos_acima_media = np.sum(np.all(notas > media, axis=1))
print(f"Alunos com notas acima da média em todas as disciplinas: {alunos_acima_media}")

max = np.max(notas, axis = 0)
print(max) # max
min = np.min(notas, axis = 0)
print(min) # min

normal = (notas - min) / (max - min)
# print(normal)
print(np.sum(np.any(normal < 0.5, axis=1)))

# PANDAS

Biblioteca amplamente usada para análise de dados. Ele fornece estruturas de dados flexíveis e permite trabalhar facilmente com dados estruturados, como tabelas. As principais características e funcionalidades do pandas incluem:

DataFrame: Uma estrutura bidimensional, semelhante a uma tabela de banco de dados ou uma planilha do Excel. Ela permite armazenar e manipular dados tabulares (com linhas e colunas).

Series: Uma estrutura unidimensional, similar a um vetor ou uma lista. É, essencialmente, uma coluna de um DataFrame.

Manipulação de dados: O pandas fornece funções para limpar, transformar, agregar e visualizar dados. Por exemplo, você pode facilmente filtrar linhas, ordenar dados, preencher valores ausentes, entre outros.

Leitura e gravação de dados: Com o pandas, é possível ler e gravar dados em vários formatos, como CSV, Excel, SQL e muitos outros.

Integração com outras bibliotecas: O pandas se integra bem com muitas outras bibliotecas populares de Python, como numpy, scipy, matplotlib e scikit-learn.

Manipulação de datas e séries temporais: O pandas possui funcionalidades robustas para trabalhar com datas, horas e séries temporais.

Performance: Embora seja uma biblioteca de alto nível, o pandas é otimizado para desempenho em muitas operações, tornando-o eficiente para conjuntos de dados grandes.

Criação e exibição de um DataFrame

In [5]:
import pandas as pd

data = {
    'Nomes': ['Ana', 'Bruno', 'Carlos'],
    'Idade': [25, 30, 35],
    'Cidade': ['Rio de Janeiro', 'São Paulo', 'Belo Horizonte']
}
df = pd.DataFrame(data)

print(df)


    Nomes  Idade          Cidade
0     Ana     25  Rio de Janeiro
1   Bruno     30       São Paulo
2  Carlos     35  Belo Horizonte


Filtro de dados:

In [ ]:

filtro = df[df['Idade'] > 28] ## lógica
print(filtro)

Estatísticas básicas:

In [ ]:

print(df.describe())


Aplicando uma função a uma coluna:

In [ ]:

df['Idade_ao_quadrado'] = df['Idade'].apply(lambda x: x**2) # função sem nome
print(df)


Tratando dados ausentes:

In [ ]:

df.fillna(0, inplace=True) # NA/NaN troca 0


Grouping

In [ ]:

data = {
    'Cidade': ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Rio de Janeiro', 'Belo Horizonte', 'Belo Horizonte'],
    'Produto': ['A', 'B', 'A', 'A', 'B', 'B'],
    'Vendas': [100, 150, 200, 250, 300, 350]
}
df = pd.DataFrame(data)
print(df)

# agrupando por cidade
vendas_cidade = df.groupby('Cidade').sum()
print(vendas_cidade)


Agrupamento por Cidade e Produto:

In [ ]:
cidade_produto = df.groupby(['Cidade', 'Produto']).sum()
print(cidade_produto)


Estatísticas básicas dos grupos:

In [ ]:
consolida_cidades = df.groupby('Cidade').describe()
print(consolida_cidades)


# Merge

In [ ]:

data1 = {
    'ID': [1, 2, 3, 4],
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana']
}
df1 = pd.DataFrame(data1)

# Segundo DataFrame
data2 = {
    'ID': [3, 4, 5, 6],
    'Idade': [25, 30, 35, 40]
}
df2 = pd.DataFrame(data2)

print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)


In [ ]:
full_join = pd.merge(df1, df2, on='ID', how='outer')
print("\nFull Join:")
print(full_join)


In [ ]:
left_join = pd.merge(df1, df2, on='ID', how='left')
print("\nLeft Join:")
print(left_join)


In [ ]:
right_join = pd.merge(df1, df2, on='ID', how='right')
print("\nRight Join:")
print(right_join)


# Exercício

Imagine que você é um analista de dados em uma grande rede de lojas. Você recebeu dois conjuntos de dados:

Um contém informações sobre os produtos (ID do produto, nome do produto e categoria).
O outro contém informações de vendas (ID do produto, quantidade vendida e preço por unidade).
Seu objetivo é combinar esses dois conjuntos de dados para obter um relatório completo que mostre o nome, categoria, quantidade vendida e receita total (quantidade vendida * preço por unidade) de cada produto.

In [6]:

produtos = {
    'ID_produto': [101, 102, 103, 104],
    'Nome_produto': ['Camiseta', 'Calça', 'Tênis', 'Chapéu'],
    'Categoria': ['Vestuário', 'Vestuário', 'Calçado', 'Acessório']
}
df_produtos = pd.DataFrame(produtos)


vendas = {
    'ID_produto': [101, 103, 104, 105],
    'Quantidade_vendida': [100, 150, 50, 60],
    'Preco_por_unidade': [20, 75, 30, 10]
}
df_vendas = pd.DataFrame(vendas)


Tarefa:

Use a função merge() para combinar os dois DataFrames com base no ID_produto.

Crie uma nova coluna chamada "Receita" que será o produto da "Quantidade_vendida" pelo "Preco_por_unidade".

Exiba o resultado final contendo 'Nome_produto', 'Categoria', 'Quantidade_vendida' e 'Receita'.

In [9]:
df_merge = pd.merge(df_produtos, df_vendas, on='ID_produto', how='outer')


df_merge['Receita'] = df_merge['Quantidade_vendida'] * df_merge['Preco_por_unidade']

print(df_merge[['Nome_produto', 'Categoria', 'Quantidade_vendida', 'Receita']])

  Nome_produto  Categoria  Quantidade_vendida  Receita
0     Camiseta  Vestuário               100.0   2000.0
1        Calça  Vestuário                 NaN      NaN
2        Tênis    Calçado               150.0  11250.0
3       Chapéu  Acessório                50.0   1500.0
4          NaN        NaN                60.0    600.0
